// Generated by CoffeeScript 1.6.2
(function() {
  var ZENITY, Zenity, bind, exec, fix, passThrough, run, status, statusOnly,
    __hasProp = {}.hasOwnProperty;

  exec = require('child_process').exec;

  module.exports = Zenity = {};

  ZENITY = 'zenity';

  run = function(mode, opts, callback) {
    return exec("" + ZENITY + " " + mode + " " + (opts.join(' ')), callback);
  };

  bind = function(name, map, handler) {
    return function(o, callback) {
      var getter, key, opts;

      opts = [];
      if (typeof o === 'object') {
        for (key in map) {
          if (!__hasProp.call(map, key)) continue;
          getter = map[key];
          if (o[key] != null) {
            opts.push(getter(o[key]));
          }
        }
      } else if (typeof callback !== 'function') {
        callback = o;
      }
      run("--" + name, opts, function(error, stdout) {
        var code;

        code = error == null ? 0 : error.code;
        if ((handler != null) && (callback != null)) {
          return process.nextTick(function() {
            return handler(status(code), stdout, callback);
          });
        }
      });
    };
  };

  fix = function(text) {
    var fixed;

    fixed = text.replace('"', '\\"');
    fixed = fixed.replace('\n', '\\n');
    return "\"" + fixed + "\"";
  };

  status = function(code) {
    return {
      cancel: code === 1,
      timeout: code === 5,
      success: code === 0
    };
  };

  statusOnly = function(status, stdout, cb) {
    return cb(status);
  };

  passThrough = function(status, stdout, cb) {
    return cb(status, stdout);
  };

  Zenity.calendar = bind('calendar', {
    text: function(v) {
      return "--text=" + (fix(v));
    },
    day: function(v) {
      return "--day=" + v;
    },
    month: function(v) {
      return "--month=" + v;
    },
    year: function(v) {
      return "--year=" + v;
    },
    dateFormat: function(v) {
      return "--date-format=" + (fix(v));
    }
  }, function(status, date, cb) {
    return cb(status, new Date(date.toString()));
  });

  Zenity.entry = bind('entry', {
    text: function(v) {
      return "--text=" + (fix(v));
    },
    entryText: function(v) {
      return "--entry-text=" + (fix(v));
    },
    hideText: function() {
      return '--hide-text';
    }
  }, passThrough);

  Zenity.error = bind('error', {
    text: function(v) {
      return "--text=" + (fix(v));
    },
    noWrap: function() {
      return '--no-wrap';
    },
    noMarkup: function() {
      return '--no-markup';
    }
  }, statusOnly);

  Zenity.fileSelection = bind('file-selection', {
    filename: function(v) {
      return "--filename=" + (fix(v));
    },
    multiple: function() {
      return '--multiple';
    },
    directory: function() {
      return '--directory';
    },
    save: function() {
      return '--save';
    },
    separator: function(v) {
      return "--separator=" + (fix(v));
    },
    confirmOverwrite: function() {
      return '--confirm-overwrite';
    },
    fileFilter: function(v) {
      return "--file-filter=" + (fix(v));
    }
  }, passThrough);

  Zenity.info = bind('info', {
    text: function(v) {
      return "--text=" + (fix(v));
    },
    noWrap: function() {
      return '--no-wrap';
    },
    noMarkup: function() {
      return '--no-markup';
    }
  }, statusOnly);

  Zenity.question = bind('question', {
    text: function(v) {
      return "--text=" + (fix(v));
    },
    noWrap: function() {
      return '--no-wrap';
    },
    noMarkup: function() {
      return '--no-markup';
    },
    okLabel: function(v) {
      return "--ok-label=" + (fix(v));
    },
    cancelLabel: function(v) {
      return "--cancel-label=" + (fix(v));
    }
  }, statusOnly);

  Zenity.textInfo = bind('text-info', {
    filename: function(v) {
      return "--filename=" + (fix(v));
    },
    editable: function() {
      return '--editable';
    },
    checkbox: function(v) {
      return "--checkbox=" + (fix(v));
    },
    okLabel: function(v) {
      return "--ok-label=" + (fix(v));
    },
    cancelLabel: function(v) {
      return "--cancel-label=" + (fix(v));
    }
  }, statusOnly);

  Zenity.warning = bind('warning', {
    text: function(v) {
      return "--text=" + (fix(v));
    },
    noWrap: function() {
      return '--no-wrap';
    },
    noMarkup: function() {
      return '--no-markup';
    }
  }, statusOnly);

  Zenity.colorSelection = bind('color-selection', {
    color: function(v) {
      return "--color=" + v;
    },
    showPalette: function() {
      return '--show-palette';
    }
  }, passThrough);

  Zenity.password = bind('password', {
    username: function() {
      return '--username';
    }
  }, passThrough);

}).call(this);
